# This is a basic workflow to help you get started with Actions
name: Build and Deploy Android
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ deploy-web ]
  pull_request:
    branches: [ deploy-web ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.16.1'
      - run: npm install --global yarn
      - run: yarn bootstrap
      - run: yarn web:release
      # Executing build with yarn
      # - name: Run bootstrap with yarn
      #   uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: bootstrap # will run `yarn bootstrap` command
      # - name: Run release with yarn
      #   uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: web:release # will run `yarn web:release` command

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: copy web via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "packages/lestraigocastweb/build/"
          target: "Desktop/lestraigocast/web"
